-- V1__initial_schema.sql — Complete current PostgreSQL schema for FlashReserve.
-- Generated to match the existing Hibernate (7.4.5.Final) + ddl-auto=update
-- production schema as inspected via \d / information_schema (2026-09-11).
-- Contains: users, events, seats, bookings, payments + all constraints/
-- indexes including the partial unique index uk_bookings_one_pending_per_seat.
-- Flyway owns this schema; Hibernate validates (ddl-auto=validate).
-- No extensions required (UUID generated by Hibernate, stored as native uuid).
-- Baseline strategy: existing populated DB -> baseline-version=1 (V1 considered applied).
-- Fresh empty DB -> V1 executes to create the full schema.

-- -------------------------------------------------------------------------
-- users
-- -------------------------------------------------------------------------
CREATE TABLE users (
    id         uuid                        NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    email      varchar(255)                NOT NULL,
    name       varchar(100)                NOT NULL,
    password   varchar(255)                NOT NULL,
    role       varchar(20)                 NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT users_role_check CHECK ((role)::text = ANY ((ARRAY['USER'::varchar,'ADMIN'::varchar])::text[]))
);

-- -------------------------------------------------------------------------
-- events
-- -------------------------------------------------------------------------
CREATE TABLE events (
    id           uuid                        NOT NULL,
    created_at   timestamp(6) with time zone NOT NULL,
    description  varchar(2000),
    event_date   timestamp(6) with time zone NOT NULL,
    name         varchar(200)                NOT NULL,
    status       varchar(20)                 NOT NULL,
    total_seats  integer                     NOT NULL,
    updated_at   timestamp(6) with time zone NOT NULL,
    venue        varchar(255)                NOT NULL,
    ticket_price numeric(10,2),
    CONSTRAINT events_pkey PRIMARY KEY (id),
    CONSTRAINT events_status_check CHECK ((status)::text = ANY ((ARRAY['DRAFT'::varchar,'PUBLISHED'::varchar,'CANCELLED'::varchar,'COMPLETED'::varchar])::text[]))
);

CREATE INDEX ix_events_status_event_date ON events USING btree (status, event_date);

-- -------------------------------------------------------------------------
-- seats (depends on events)
-- -------------------------------------------------------------------------
CREATE TABLE seats (
    id          uuid                        NOT NULL,
    created_at  timestamp(6) with time zone NOT NULL,
    seat_number varchar(20)                 NOT NULL,
    status      varchar(20)                 NOT NULL,
    updated_at  timestamp(6) with time zone NOT NULL,
    version     bigint                      NOT NULL,
    event_id    uuid                        NOT NULL,
    CONSTRAINT seats_pkey PRIMARY KEY (id),
    CONSTRAINT uk_seats_event_id_seat_number UNIQUE (event_id, seat_number),
    CONSTRAINT seats_status_check CHECK ((status)::text = ANY ((ARRAY['AVAILABLE'::varchar,'HELD'::varchar,'BOOKED'::varchar])::text[])),
    CONSTRAINT fkn8dwqflg9k82ygrbsseghd7ca FOREIGN KEY (event_id) REFERENCES events (id)
);

-- -------------------------------------------------------------------------
-- bookings (depends on users, events, seats)
-- -------------------------------------------------------------------------
CREATE TABLE bookings (
    id         uuid                        NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    expires_at timestamp(6) with time zone,
    status     varchar(20)                 NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    event_id   uuid                        NOT NULL,
    seat_id    uuid                        NOT NULL,
    user_id    uuid                        NOT NULL,
    CONSTRAINT bookings_pkey PRIMARY KEY (id),
    CONSTRAINT bookings_status_check CHECK ((status)::text = ANY ((ARRAY['PENDING'::varchar,'CONFIRMED'::varchar,'EXPIRED'::varchar,'CANCELLED'::varchar])::text[])),
    CONSTRAINT fkeyog2oic85xg7hsu2je2lx3s6 FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk2ww82bk3npaiyu9oeehwtt2q3 FOREIGN KEY (event_id) REFERENCES events (id),
    CONSTRAINT fkhmf8yyefriw5ski3jibaua6n FOREIGN KEY (seat_id) REFERENCES seats (id)
);

CREATE INDEX ix_bookings_event_id_status ON bookings USING btree (event_id, status);
CREATE INDEX ix_bookings_expires_at ON bookings USING btree (expires_at);
CREATE INDEX ix_bookings_seat_id_status ON bookings USING btree (seat_id, status);
CREATE INDEX ix_bookings_user_id_status ON bookings USING btree (user_id, status);

-- Partial unique index: at most one PENDING booking per seat (SEC-03 defense-in-depth).
-- Predicate and name must stay exactly as required: status = 'PENDING'.
CREATE UNIQUE INDEX uk_bookings_one_pending_per_seat
ON bookings (seat_id)
WHERE status = 'PENDING';

-- -------------------------------------------------------------------------
-- payments (depends on bookings)
-- -------------------------------------------------------------------------
CREATE TABLE payments (
    id                  uuid                        NOT NULL,
    amount              numeric(12,2)               NOT NULL,
    created_at          timestamp(6) with time zone NOT NULL,
    payment_reference   varchar(100),
    status              varchar(20)                 NOT NULL,
    updated_at          timestamp(6) with time zone NOT NULL,
    booking_id          uuid                        NOT NULL,
    razorpay_order_id   varchar(64),
    razorpay_payment_id varchar(64),
    razorpay_refund_id  varchar(64),
    CONSTRAINT payments_pkey PRIMARY KEY (id),
    CONSTRAINT uk_payments_booking_id UNIQUE (booking_id),
    CONSTRAINT payments_status_check CHECK ((status)::text = ANY ((ARRAY['PENDING'::varchar,'SUCCESS'::varchar,'FAILED'::varchar,'REFUNDED'::varchar])::text[])),
    CONSTRAINT fkc52o2b1jkxttngufqp3t7jr3h FOREIGN KEY (booking_id) REFERENCES bookings (id)
);
