package com.soubhagya.flashreserve.security;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.UUID;

import com.soubhagya.flashreserve.entity.User;
import com.soubhagya.flashreserve.entity.enums.UserRole;

import org.junit.jupiter.api.Test;
import org.springframework.test.util.ReflectionTestUtils;

/**
 * Unit tests for the JWT secret guard and token round-trip.
 * No real secret value is ever printed: assertions check message FRAGMENTS,
 * never the configured value, and test secrets are throwaway test-only
 * values defined inline (never the developer's local secret).
 */
class JwtServiceTest {

	private static final String VALID_TEST_SECRET =
			"unit-test-only-secret-0123456789abcdef0123456789abcdef";

	private static final String KNOWN_PLACEHOLDER_SECRET =
			"change-me-in-local-environment-only-min-32-chars-long";

	private static final long EXPIRATION_MS = 3600000L;

	private User userWithRole(UserRole role) {
		User user = new User("Load Test", "loadtest-" + UUID.randomUUID() + "@example.com",
				"irrelevant-bcrypt-hash", role);
		// User.id has no setter (generated by JPA); inject a test id directly.
		ReflectionTestUtils.setField(user, "id", UUID.randomUUID());
		return user;
	}

	@Test
	void rejectsKnownPlaceholderSecret() {
		IllegalStateException ex = assertThrows(IllegalStateException.class,
				() -> new JwtService(KNOWN_PLACEHOLDER_SECRET, EXPIRATION_MS));
		assertTrue(ex.getMessage().contains("known placeholder"));
		// The error must never echo the configured secret value.
		assertFalse(ex.getMessage().contains(KNOWN_PLACEHOLDER_SECRET));
	}

	@Test
	void rejectsTooShortSecret() {
		IllegalStateException ex = assertThrows(IllegalStateException.class,
				() -> new JwtService("short-secret", EXPIRATION_MS));
		assertTrue(ex.getMessage().contains("at least 32 characters"));
		assertFalse(ex.getMessage().contains("short-secret"));
	}

	@Test
	void userTokenRoundTripPreservesIdentityAndRole() {
		JwtService jwtService = new JwtService(VALID_TEST_SECRET, EXPIRATION_MS);
		User user = userWithRole(UserRole.USER);
		String token = jwtService.generateToken(user);

		var principal = jwtService.parseToken(token);
		assertEquals(user.getId(), principal.id());
		assertEquals(user.getEmail(), principal.email());
		assertEquals(UserRole.USER, principal.role());
	}

	@Test
	void adminTokenRoundTripPreservesAdminRole() {
		JwtService jwtService = new JwtService(VALID_TEST_SECRET, EXPIRATION_MS);
		User admin = userWithRole(UserRole.ADMIN);
		String token = jwtService.generateToken(admin);

		var principal = jwtService.parseToken(token);
		assertEquals(UserRole.ADMIN, principal.role());
	}

	@Test
	void tokenSignedWithDifferentSecretIsRejected() {
		JwtService issuer = new JwtService(VALID_TEST_SECRET, EXPIRATION_MS);
		JwtService verifier = new JwtService(
				"a-completely-different-unit-test-secret-value-0123456789", EXPIRATION_MS);
		String token = issuer.generateToken(userWithRole(UserRole.USER));

		assertThrows(Exception.class, () -> verifier.parseToken(token));
	}

}
